version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app