# fly.toml app configuration file generated for repairify-blog-part3 on 2024-03-22T10:57:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'repairify-blog-part3'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
